# We start by reviewing the candidate report generated by the software. To group the paternities and sibling relationships, we will separate the two files and organize the data accordingly.


# load libraries
library(tidyr)
library(writexl)
library(readxl)

#Pathway to input data and output 
input_path <- "C:/Users/Desktop/Miranda_dnaview/Validación de datos/Input/prueba/"
output_path <- "C:/Users/Desktop/Miranda_dnaview/Validación de datos/Input/prueba/"

# List all .txt files in the input directory
txt_files <- list.files(input_path, pattern = "\\.txt$", full.names = TRUE)

# Initialize a list to store processed data frames
processed_files <- list()
process_text_file <- function(path, n) {
  # Read the content of the .txt file
  content <- readLines(path, n = n)
  
  # Split the content into families and their respective victim information
	# pattern # +number +.
  family_indices <- grep("^#\\d+\\. family", content)
  
  families <- content[family_indices]
  
  # Create a list to hold victim information for each family
  victim_info <- lapply(seq_along(family_indices), function(i) {
    if (i < length(family_indices)) {
      content[(family_indices[i] + 1):(family_indices[i + 1] - 1)]
    } else {
      content[(family_indices[i] + 1):length(content)]
    }
  })
  
  # Initialize an empty dataframe to store the information
  df <- data.frame(FAM = character(),
                   VIC_before_vs = character(),
                   VIC_after_vs = character(),
                   Folio = character(),
                   VIC_folio = character(),
                   stringsAsFactors = FALSE)
  
  # Iterate through families and victim information
  for (i in seq_along(families)) {
    # Extract the family name
    family_name <- families[i]
    
    # Extract the date from the family name
    Folio <- gsub(".*family\\s(\\d+)=.*", "\\1", family_name)
    
    # Filter out lines containing "VIC"
    victim_lines <- victim_info[[i]][!grepl("^\\s*VIC", victim_info[[i]])]
    
    # Process each line of victim information
    for (j in seq_along(victim_lines)) {
      line <- victim_lines[j]
      
      # Check if the line contains "vs"
      if (grepl("\\svs", line)) {
        # Split the line before and after "vs"
        parts <- strsplit(line, "\\s+vs\\s+")[[1]]
        before_vs <- parts[1]
        after_vs <- parts[2]
        
        # Extract second and third elements for VIC_folio
        folio_parts <- strsplit(before_vs, "\\s+")[[1]][c(4, 3)] # Change the order here
        VIC_folio <- paste(folio_parts, collapse = " ")
        
        # Append the family name and victim information to the dataframe
        df <- rbind(df, data.frame(FAM = family_name,
                                   VIC_before_vs = before_vs,
                                   VIC_after_vs = after_vs,
                                   Folio = Folio,
                                   VIC_folio = VIC_folio,
                                   stringsAsFactors = FALSE))
      }
    }
  }
  
  # Splitting the VIC_after_vs column into "Letter" and "Value"
  df <- separate(df, VIC_after_vs, into = c("Pedigree", "Value"), sep = " ", extra = "merge")
  
  # Splitting the "Value" column into two columns based on "="
  df <- separate(df, Value, into = c("Kinship", "Value"), sep = "=")
  
  # Fill empty cells conditionally
  for (i in 2:nrow(df)) {
    if (df[i, "VIC_before_vs"] == "") {
      df[i, "VIC_before_vs"] <- df[i - 1, "VIC_before_vs"]
      df[i, "VIC_folio"] <- df[i - 1, "VIC_folio"] # Fill VIC_folio with the previous row's value
    }
  }
  
  # Return the modified dataframe
  return(df)
}



# Loop through each .txt file
for (file in txt_files) {
  tryCatch({
    # Process the file
    processed_df <- process_text_file(file, n = 500000)
    
    # Extract file name without extension
    file_name <- gsub("\\.txt$", "", basename(file))
    
    # Save the processed data frame to an .xlsx file
    output_file_name <- paste0("Process_", file_name, ".xlsx")
    output_file_path <- file.path(output_path, output_file_name)
    write_xlsx(processed_df, output_file_path)
    
    # Store the processed data frame in the list
    processed_files[[file_name]] <- processed_df
    
    cat("Processed and saved:", output_file_path, "\n")
  }, error = function(e) {
    cat("Error processing file:", file, "\n")
    print(e)
  })
}


#################################Part two ####################################################
#With the processed files, we separate the files by kinship, pi-paternity, si-sibling relationship, 
#LL-for the first two highest LRs of the same folio and id- for similar profiles.

library(readxl)
library(writexl)
library(dplyr)


# Set your input and output folder paths
input_folder <- "C:/Users/Miranda Córdova/Desktop/Miranda_dnaview/Validación de datos/ejercicio/"
output_folder <- "C:/Users/Miranda Córdova/Desktop/Miranda_dnaview/Validación de datos/ejercicio_separate/"

# Get list of all Excel files in the input folder
excel_files <- list.files(input_folder, pattern = "\\.xlsx$", full.names = TRUE)
# # Function to filter rows based on specified kinship values
# excel_files<- excel_files[-1]
filter_kinship <- function(input_file, kinship_value) {
  # Read the Excel file
  data <- read_excel(input_file)

  # Filter rows with specified kinship value
  filtered_data <- data %>%
    filter(Kinship == kinship_value)

  return(filtered_data)
}

# Define the kinship values
kinship_values <- c('LL', 'pi', 'id', 'sib')

# Iterate through each kinship value
for (kinship_value in kinship_values) {
  # Initialize an empty data frame to store filtered data for the current kinship value
  aggregated_filtered_data <- data.frame()

  # Iterate through each Excel file
  for (file in excel_files) {
    # Filter rows based on the current kinship value
    filtered_data <- filter_kinship(file, kinship_value)

    # Aggregate filtered data
    aggregated_filtered_data <- rbind(aggregated_filtered_data, filtered_data)
    aggregated_filtered_data$Value <- as.numeric(aggregated_filtered_data$Value)
  }

  # Save filtered data to a new Excel file in output folder
  output_file <- file.path(output_folder, paste0("filtered_", kinship_value, ".xlsx"))
  write_xlsx(aggregated_filtered_data, output_file)

  cat("Filtered data for kinship value", kinship_value, "saved to:", output_file, "\n")
}
#######################################################################################


#For beggest files 
#################################################

library(readxl)
library(dplyr)
library(writexl)

# Function to split a DataFrame into smaller chunks
split_dataframe <- function(data, chunk_size) {
  split_indices <- seq(1, nrow(data), by = chunk_size)
  split_data <- lapply(split_indices, function(start_index) {
    end_index <- min(start_index + chunk_size - 1, nrow(data))
    data[start_index:end_index, ]
  })
  return(split_data)
}

# Function to filter rows based on specified kinship values
filter_kinship <- function(input_file, kinship_value) {
  # Read the Excel file
  data <- read_excel(input_file)
  
  # Filter rows with specified kinship value
  filtered_data <- data %>%
    filter(Kinship == kinship_value)
  
  return(filtered_data)
}

# Define the kinship values
kinship_values <- c('sib')

# Define the maximum number of rows per chunk to avoid exceeding Excel limits
max_rows_per_chunk <- 1048576 - 1  # 1 row for headers

# Iterate through each kinship value
for (kinship_value in kinship_values) {
  # Initialize an empty data frame to store filtered data for the current kinship value
  aggregated_filtered_data <- data.frame()
  
  # Iterate through each Excel file
  for (file in excel_files) {
    # Filter rows based on the current kinship value
    filtered_data <- filter_kinship(file, kinship_value)
    
    # Aggregate filtered data
    aggregated_filtered_data <- rbind(aggregated_filtered_data, filtered_data)
  }
  
  # Convert Value column to numeric if it exists
  if ("Value" %in% colnames(aggregated_filtered_data)) {
    aggregated_filtered_data$Value <- as.numeric(aggregated_filtered_data$Value)
  }
  
  # Split the aggregated data if it exceeds the row limit
  if (nrow(aggregated_filtered_data) > max_rows_per_chunk) {
    # Split the DataFrame into chunks
    split_data <- split_dataframe(aggregated_filtered_data, max_rows_per_chunk)
    
    # Save each chunk to a separate Excel file
    for (i in seq_along(split_data)) {
      output_file <- file.path(output_folder, paste0("filtered_", kinship_value, "_part_", i, ".xlsx"))
      write_xlsx(split_data[[i]], output_file)
      cat("Filtered data for kinship value", kinship_value, "part", i, "saved to:", output_file, "\n")
    }
  } else {
    # Save the filtered data to a single Excel file
    output_file <- file.path(output_folder, paste0("filtered_", kinship_value, ".xlsx"))
    write_xlsx(aggregated_filtered_data, output_file)
    cat("Filtered data for kinship value", kinship_value, "saved to:", output_file, "\n")
  }
}


